### ISSUE TITLE
my chrome on ubuntu saves at 1513x1136

### ISSUE THREAD

**Issue by orrrobert** [erikbernheim/img-labeler#12]
I have the browser zoom at 100%

**Comment by erikbernheim** [comment]
Which image URL is this occurring on?

**Comment by orrrobert** [comment]
It happens on all images including the demo image

**Comment by erikbernheim** [comment]
Is this when making a mask from scratch, or using the mask-import function?

**Comment by orrrobert** [comment]
from scratch

**Comment by erikbernheim** [comment]
What resolution is your monitor?

**Comment by orrrobert** [comment]
1920x1080

**Comment by erikbernheim** [comment]
Any custom monitor scaling?

**Comment by orrrobert** [comment]
I dont think so
![Screenshot from 2020-03-23 16-58-17](https://user-images.githubusercontent.com/32775279/77370929-9f2e8680-6d27-11ea-986e-34e87d28feca.png)

**Comment by erikbernheim** [comment]
I'm sorry about that. I'll send you some troubleshooting commands to run in debug console in a hour and a half or so

**Comment by orrrobert** [comment]
cool thanks for the project

**Comment by erikbernheim** [comment]
This is a tough one, the most relevant command I can think of is this.
`window.devicePixelRatio`
Let me know the return value + any precision

**Comment by orrrobert** [comment]
window.devicePixelRatio
1.2999999523162842

**Comment by erikbernheim** [comment]
Alright, that should be one exactly. Can you hit ctrl+0, or zooming in/out to try and make that equal one?

**Comment by orrrobert** [comment]
I can only zoom in increments of 5 somewhere between 75 and 80 percent is 1

**Comment by erikbernheim** [comment]
What chrome version are you running?

**Comment by orrrobert** [comment]
77.0.3865.120

**Comment by erikbernheim** [comment]
Try and update to version 80

**Comment by orrrobert** [comment]
i think firefox did the same.. I can check that

**Comment by orrrobert** [comment]
oh.. I think firefox wont run it..
I can try to upgrade chrome

**Comment by erikbernheim** [comment]
img-labeler doesn't support FF, so it likely doesn't work

**Comment by orrrobert** [comment]
ok version 80 saves as 1134x852

**Comment by erikbernheim** [comment]
Shoot, that's still the wrong resolution

What number does window.devicePixelRatio return now

**Comment by orrrobert** [comment]
oops it stayed at 75% zoom when I loaded version 80. I went back to 100% and it's back to window.devicePixelRatio
1.2999999523162842

**Comment by orrrobert** [comment]
Version 80.0.3987.149

**Comment by erikbernheim** [comment]
What physical size is your display? Are you running on a laptop with a retina display (I.E. XPS13 or MacBook Pro?)

**Comment by orrrobert** [comment]
15" hp 8560w

**Comment by Jax05** [comment]
Updating Chrome to 81.0.4044.122 fixed this issue for me.

**Comment by erikbernheim** [comment]
@Jax05 glad you were able to find a solution to your issue. It looks like all of these are stemming from one thing or another causing window.devicePixelRatio to be off.

**Comment by ahs8w** [comment]
I'm on Chrome Version 83.0.4103.106 and was also having issues with the saved image being double the normal size.  Your comment about window.devicePixelRatio was the solution.  Setting that value to be 1 (it defaulted to 2) in the console allowed me to save properly.  Cool app!!

**Comment by erikbernheim** [comment]
@ahs8w I didn't realize window.devicePixelRatio was writable. Thank you for commenting, this is the last piece of the puzzle to close this issue.

**Comment by erikbernheim** [comment]
devicePixelRatio is writable via console, but js doesn't have write permissions. I added a scaling param to the svg export. The [fix](https://github.com/erikbernheim/img-labeler/commit/71468f392f6bf092eedb8b36635fffe7eccf18fc#diff-8971e085ff1e90f77ba6c4156d5e50e5) is live now, let me know if anyone is still having the issue.
