### ISSUE TITLE
Add button for saving to history

### ISSUE THREAD

**Issue by meh-meh** [erikbernheim/img-labeler#15]
I have been adding random layers to ensure data saves to history. History doesn't appear to be updated for moved control points or layer order changes.

**Comment by erikbernheim** [comment]
I will set history to update on moved control points and layer order changes. Do you think a button will still be necessary?

**Comment by meh-meh** [comment]
Only for peace of mind, but as long as I can be confident in refreshing the tab after I manipulate something, then it's not necessary

**Comment by erikbernheim** [comment]
Resolved. Button added under the history list. Make sure it the mask has been added to the history list before closing tab.
