### ISSUE TITLE
pulled in mask  

### ISSUE THREAD

**Issue by bigbalthazor** [erikbernheim/img-labeler#17]
I was deleting the layers I didn't want and I had a lane line left over but no layer to go with it. 

"my car" is still in the lower half of the picture i didn't snip. 
![image](https://user-images.githubusercontent.com/61742003/77457181-b7a7ab00-6dd2-11ea-90c0-8912dd069932.png)

**Comment by erikbernheim** [comment]
What image did this occur on?

**Comment by bigbalthazor** [comment]
that was 17.. or 14 but it does it to any image. just delete all the layers and one will always be left. the workaround is just to refresh.

**Comment by erikbernheim** [comment]
Resolved
