### ISSUE TITLE
Request: 'Select from repo' interface

### ISSUE THREAD

**Issue by meh-meh** [erikbernheim/img-labeler#21]
Perhaps this could be more configurable in the future, but for now it would be great if you could type in a number and have that image load from the comma10k repo. 

To make it extra useful, perhaps it could have some URL parameters to allow it to be shared (e.g. "/img-labeler?id=0923&mask=true")

**Comment by meh-meh** [comment]
I assume this could be partially implemented with the code that finds the related mask for the image, just applied to the actual image in the /img folder of the repo.

**Comment by erikbernheim** [comment]
Cleaning up old issues that have been resolved.
