### ISSUE TITLE
Support going to a particular image on the labeller via a URL

### ISSUE THREAD

**Issue by nuwandavek** [erikbernheim/img-labeler#31]
It'll be great to allow annotators to go to a particular image to annotate via the spreadsheet or some other page by clicking on a URL. We could add an image name param to the URL to achieve this.

**Comment by ed2k** [comment]
#36

**Comment by erikbernheim** [comment]
Cleaning up old issues that have been resolved.
Example: https://erikbernheim.github.io/img-labeler/?imageNumber=r032
