### ISSUE TITLE
Gets into state where I can't move old points

### ISSUE THREAD

**Issue by geohot** [erikbernheim/img-labeler#4]
Repro:

1) Click reset
2) Draw a square (note that you can move the points)
3) Click a new point
4) Press undo
5) Can't drag the square

**Comment by pjlao307** [comment]
Also, when creating a poly and clicking an existing point (as if to move it)

**Comment by meh-meh** [comment]
Not sure if it's worth a new issue, but a good fix for this issue will likely introduce a better/more reliable way to cancel a new polygon. I tend to instinctively hit escape or right click the mouse to cancel the layer, and as @geohot says, hitting undo will break the dragability.

**Comment by meh-meh** [comment]
Also worth noting that an attempt to drag a point when in this state causes a point to be created when mouse button is released.

**Comment by erikbernheim** [comment]
Half resolved, original issue has been resolved, however existing points still appear to be draggable (but are not) when creating a new layer.

**Comment by erikbernheim** [comment]
Fully resolved
