### ISSUE TITLE
Request: Make  export preview always start at a minimum of 20% opacity

### ISSUE THREAD

**Issue by doktorsleepelss** [erikbernheim/img-labeler#52]
So I usually draw my polygons with opacity set to 0% because you get clearer view of whatever you're outlining this way. After I complete the polygon, I would want to use export preview immediately after to see how the final polygon looks at the pixel level.  Problem is that when I press O with 0% opacity, it initially looks like nothing changed, and it's not clear if it's on or not. Then I remember I have to increase opacity to see the mask.  It would save me an arrow key press and some initial confusion to just set opacity at 20% immediately after pressing O. I really can't think of any cicumstance where you'd want to an invisble preview rigth after pression O.

If opacity is set to anything other 0% when  you enable export preview, then continue to match the opacity like it does now.

**Comment by erikbernheim** [comment]
Resolved.
